# https://github.com/slsa-framework/slsa-github-generator
# https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/go/README.md
# https://github.com/slsa-framework/slsa-verifier

name: SLSA go releaser
on:
  workflow_dispatch:
  release:
    types: ["created"]
permissions: read-all
jobs:
  args:
    runs-on: ubuntu-latest
    outputs:
      commit-date: "${{ steps.ldflags.outputs.commit-date }}"
      commit: "${{ steps.ldflags.outputs.commit }}"
      version: "${{ steps.ldflags.outputs.version }}"
      tree-state: "${{ steps.ldflags.outputs.tree-state }}"
    steps:
      - id: checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - id: ldflags
        run: |
          echo "commit-date=$(git log --date=iso8601-strict -1 --pretty=%ct)" >> "$GITHUB_OUTPUT"
          echo "commit=$GITHUB_SHA" >> "$GITHUB_OUTPUT"
          echo "version=$(git describe --tags --always --dirty | cut -c2-)" >> "$GITHUB_OUTPUT"
          echo "tree-state=$(if git diff --quiet; then echo "clean"; else echo "dirty"; fi)" >> "$GITHUB_OUTPUT"
  build-amd64:
    permissions:
      id-token: write  # To sign the provenance.
      contents: write  # To upload assets to release.
      actions: read    # To read the workflow path.
    needs: args
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.2.2
    with:
      go-version: "1.19"
      evaluated-envs: "COMMIT_DATE:${{needs.args.outputs.commit-date}}, COMMIT:${{needs.args.outputs.commit}}, VERSION:${{needs.args.outputs.version}}, TREE_STATE:${{needs.args.outputs.tree-state}}"
      upload-assets: true
      config-file: ".slsa-goreleaser.amd64.yml"
  build-arm64:
    permissions:
      id-token: write  # To sign the provenance.
      contents: write  # To upload assets to release.
      actions: read    # To read the workflow path.
    needs: args
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.2.2
    with:
      go-version: "1.19"
      evaluated-envs: "COMMIT_DATE:${{needs.args.outputs.commit-date}}, COMMIT:${{needs.args.outputs.commit}}, VERSION:${{needs.args.outputs.version}}, TREE_STATE:${{needs.args.outputs.tree-state}}"
      upload-assets: true
      config-file: ".slsa-goreleaser.arm64.yml"
